### PR TITLE
Language improvements to the how_it_works.rst doc

### PR DESCRIPTION
**Pull request by benbp**

### CODE REVIEW

**Comment by benbp** [comment]
@christineday @bossidy @heckj

**Comment by benbp** [comment]
Needs rebase, on it.

**Comment by benbp** [comment]
FYI @heckj I switched active and passive discovery, but let me know if this is mistaken. I had thought "active" was meant for netbooting, whereas "passive" was for simple information querying (SNMP, IPMI).

**Comment by heckj** [comment]
Works for me, I'm sure I'm not consistent there with my active/passive patterns

**Pull request merged**
