### PR TITLE
breaking up content into a separate users and development guide

### PR DESCRIPTION
**Pull request by heckj**
I added an index.rst to "rackhd" and "devguide" directories so I could include that in the top level TOC for referencing the subdocuments. For the life of me, I'm not sure why one is getting numbered in the top index, but not the other.

I moved content specific to developing on the code into 'devguide' and the rest I left where it was, but titled the index.rst in that directory as "users guide" to differentiate the content

### CODE REVIEW

**Comment by bossidy** [comment]
Should I merge this?

**Comment by heckj** [comment]
give me another day with it to see if I can work out the quirks from my weekend trials

**Comment by bossidy** [comment]
Sure...thanks.

**Comment by heckj** [comment]
@bossidy found the last tidbit - apparently you're not supposed to use `:numbered:` in sub-tables-of-contents in Sphinx. Removing that from the sub-index's resolved the numbering issue.

**Comment by heckj** [comment]
@bossidy I'm loading up the data just fine - it's all appearing as I expected it would - they appear as subbullets to me now instead of all inlined content, but it's all there. Are you seeing something different?

**Comment by bossidy** [comment]
When I navigate to http://rackhd.readthedocs.org/en/latest/rackhd/index.html, There is only a table of contents on the page. There is no content on the right side of the page. Compare that with http://rackhd.readthedocs.org/en/latest/how_it_works.html. All the other equivalent sections (sections 1 - 7) are just one html page with a table of contents in the left frame.

**Comment by bossidy** [comment]
strictly speaking it works in a fashion.  But it is different from the rest of the site and it adds another navigation layer.

**Comment by heckj** [comment]
Got it.  I'll dig there. My intent was to break things up, but not add another layer of navigation

**Comment by bossidy** [comment]
OK. If it turns into a time sink, I'm more than willing to set up the dev and user guides as individual rsts that use 'includes' to import the subsections.

**Pull request merged**
