### PR TITLE
Adding sharedKey information to configuration docs

### PR DESCRIPTION
**Pull request by tldavies**
resolves RackHD/RackHD#256

### CODE REVIEW

**Comment by heckj** [comment]
You might add to the PR description "resolves https://github.com/RackHD/RackHD/issues/256", and do you have a snippet of code (python, nodejs, bash, etc) as an example that would generate a relevant key?

**Comment by tldavies** [comment]
@heckj better? I add a openssl comandline example to generate a key

**Comment by heckj** [comment]
👍 thanks!

**Comment by VulpesArtificem** [comment]
👍

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Comment by tldavies** [comment]
@RackHD/corecommitters please merge

**Comment by pscharla** [comment]
@RackHD/corecommitters @heckj Please merge when you get a chance.  This one is good to go.

**Pull request merged**
