### PR TITLE
add links to vagrant and ansible, slight reformat for prereq note

### PR DESCRIPTION
**Pull request by heckj**
updating demo/quick start installation instructions to match updates with bintray

### CODE REVIEW

**Comment by heckj** [comment]
updated docs will only be correct after https://github.com/RackHD/RackHD/pull/5 has been merged

**Comment by bossidy** [comment]
Will the likely open sourcer know what Ansible and Vagrant are? Should I add them to the glossary with  basic descriptions?

**Comment by heckj** [comment]
@bossidy they're super well known in the open source community, and I added the hyperlinks in the docs just to make sure they could be "looked up" if the reader wasn't familar - don't think we need to add it into the glossary, but not opposed if you feel strongly about it.

**Comment by bossidy** [comment]
If someone uses the "Clone in Desktop" button to clone the repo, will it recurse as needed or do they have to use "git clone --recursive https://github.com/RackHD/RackHD"?

**Comment by bossidy** [comment]
Nevermind...it does recurse.....

**Comment by bossidy** [comment]
Don't think we need anything if they are well-known. Thanks.

**Comment by bossidy** [comment]
Do you want me to merge this or wait for other people to look at it?

**Comment by bossidy** [comment]
This sentence doesn't mean anything to me, but it can stay as is if coders would know what it means:

The ansible roles places in a Procfile and installs `node-foreman`_ to run all
the applications from a single script.

??(The ansible role ADDS a Procfile and installs `node-foreman`_ to run 
the applications from a single script.)??

**Comment by benbp** [comment]
No I agree @bossidy that sentence isn't quite correct.

**Comment by heckj** [comment]
darnit - sorry - I merged thinking you were suggesting I should before fixing that. fix coming in a sec

**Pull request merged**
