### PR TITLE
Custom sphinx theme based on REX-ray docs.

### PR DESCRIPTION
**Pull request by rolandpoulter**
Updated docs to look more similar to the REX-ray docs.

image
image

### CODE REVIEW

**Comment by benbp** [comment]
FYI @bossidy, this looks like it has a wider default view, so we probably won't need to do the table grid width updates to get the text to wrap and remove the scroll? Or maybe it's still a good idea, idk.

**Comment by heckj** [comment]
+1!!! @christineday this should do it!

**Comment by benbp** [comment]
:+1: under protest because I like the default better.

**Comment by bossidy** [comment]
I'll review the tables.

**Comment by christineday** [comment]
Great job Ronald!!!  One comment...I like the TOC to display on the left opposed the drop-down on the top.  Can we easily change that back (keeping the same structure that is currently displaying from the drop-down)?

**Comment by rolandpoulter** [comment]
I preferred the menu from the last design. I'm sure we can, but I don't know how so it would take some investigation in order to preserve the full menu structure from the last design. It may also cause trouble with the `scrollspy` behavior.

**Comment by christineday** [comment]
Thanks Ronald.  let me know if there is anything I can do to help or test.

**Comment by heckj** [comment]
@rolandpoulter would appreciate you doing the digging - if it becomes untenable due to scrollspy behaviour, let us know and lay out what the options are for working around it, disabling it, etc.

**Comment by rolandpoulter** [comment]
I won't be able to look into it until next week. Thanks @heckj

**Pull request merged**
