### PR TITLE
Update readthedocs for ipmi alerts

### PR DESCRIPTION
**Pull request by abildw**
can be merged now that affiliated code changes went in last week

### CODE REVIEW

**Comment by heckj** [comment]
double checking - is this still valid after we had to regress on some of the SEL/SDR changes from @brianparry and @uppalk1 ?

Functionally looks good, I just don't know if it's accurate to the code.

**Comment by brianparry** [comment]
@heckj - this doc change goes along with https://github.com/RackHD/on-tasks/pull/83  which was just reverted.

**Comment by brianparry** [comment]
@heckj I think we'll ultimately want the poller output to look like this, but we need to hold off on these doc changes until we sort out how to deal with the compatibility issues.

**Comment by heckj** [comment]
perfect, thanks @brianparry  - I'm going to edit this PR to put a message in to "HOLD" the PR until those changes go back in. No use in killing this and having to redo it later.

**Comment by abildw** [comment]
updated with new format 
@geoff-reid @brianparry @srinia6 @dalebremner

**Comment by brianparry** [comment]
:+1:

**Comment by geoff-reid** [comment]
:+1:

**Comment by heckj** [comment]
WOOT! mergin!

**Pull request merged**
