### PR TITLE
Vagrant diagram

### PR DESCRIPTION
**Pull request by heckj**
my coffee-shop experiment - sketched the diagram and updated the docs all from my iPad to see if I could make it work. Only downside is I can't see the results rendered into HTML locally, so setting up a PR to pull down at home and try it out

### CODE REVIEW

**Comment by benbp** [comment]
:+1: this is kind of hilarious.

**Comment by heckj** [comment]
update looks like this:

screen shot 2015-12-08 at 9 22 13 am

**Comment by bossidy** [comment]
Would you like me to get our illustrator to make a glamorous version of the diagram?

**Comment by heckj** [comment]
lol, yeah - that would be good.

**Comment by bossidy** [comment]
Chris is on it...

**Comment by bossidy** [comment]
BTW, the diagram is a great addition...

**Comment by christineday** [comment]
How's this?
vagrant

**Comment by heckj** [comment]
Lovely, I'll update the PR!

**Pull request merged**
