### PR TITLE
adding annotation for setting arbitrary tag

### PR DESCRIPTION
**Pull request by heckj**
reference slack conversation with @codenrhoden from 25apr2016

fyi @zyoung51 - did I get this correct?

. @codenrhoden

### CODE REVIEW

**Comment by codenrhoden** [comment]
I can confirm that the example added here worked for me.

Only thing I noticed is that manually applying a tag to a node, when using a tag that does not already exist, does not result in a tag that is returned when listing all tags via `GET api/1.1/tags`.

**Comment by zyoung51** [comment]
@heckj: Documentation appears under nodes: http://rackhd.readthedocs.org/en/latest/rackhd/index.html#api-commands-for-nodes.  Might be worth linking or copying what is already there to keep it consistent?

**Comment by benbp** [comment]
👍  along with @zyoung51's suggestion.

**Comment by heckj** [comment]
yeah, I'll shift it up there, thanks! Update shortly...

**Comment by heckj** [comment]
@zyoung51 @benbp I'm a little concerned it's not clear the piece I added was about externally set/arbitrary tags vs. most of the API being focused on the rules mechanisms. Does this read OK?

**Comment by zyoung51** [comment]
@heckj FWIW, this is what is currently in the nodes documentation.  I'm ok with duplicating the documentation and not putting a link.  Would you want to bring in the list/delete references to nodes/:nodeid/tags as well?
```
**Add a tag to a node**

::

    PATCH /api/1.1/nodes/<id>/tags

::

    curl -H "Content-Type: application/json" -X PATCH -d '{ "tags": [<list of tags>]}' <server>/api/1.1/nodes/<id>/tags
```

**Comment by heckj** [comment]
Oh crap, now I understand your comment. Thanks, I'll update to reference the node API to enable this

**Comment by heckj** [comment]
@zyoung51 this should be way more sane now

**Comment by zyoung51** [comment]
+1

**Pull request merged**
