### PR TITLE
Fix taskTimeout and add dhcpLeasesPath docs

### PR DESCRIPTION
**Pull request by rolandpoulter**
* Add documentation for dhcpLeasesPath to configuration
* Change $taskTimeout to _taskTimeout

### CODE REVIEW

**Comment by heckj** [comment]
👍

**Comment by benbp** [comment]
Fixes https://github.com/RackHD/RackHD/issues/39

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
merge after https://github.com/RackHD/on-tasks/pull/234 & https://github.com/RackHD/on-taskgraph/pull/116

**Pull request merged**
