### PR TITLE
draft content dump

### PR DESCRIPTION
**Pull request by heckj**
* broke up the structure of the document into several flat files
 * created rough definition of what files should exist based on writing "introduction.rst"
 * migrated all older markdown documents from original doc sets and converted roughly to rst format
  * tables are still crappy in the quick conversion effort
* added basic images and diagrams (and source files where I had them) to annotate documentation
* created how it works, glossary entries, and background detail to throw out initial content 
* made basic doc links and interlinked some of the documents
* found and set examples for various rst formatting markup, including files, preformatted text blocks, etc

I'm not deeply tied to these specific file structures, just trying to put something in place so we can edit this  forward and lay down a base of content to work with. FYI - all content in here should be considered draft - it's all first cut from my head, or ported from older documentation and roughly converted to rst format

### CODE REVIEW

**Comment by heckj** [comment]
While I'm continuing to work on this : some of the documentation I've ported in here is specific to the workflow engine and was created originally in markdown format. I've converted them as effectively as I can, but had a tremendous amount of trouble getting the tables to convert into something reasonable in reStructuredText markup format. There's several sections where we're documenting internal APIs, JSON data formats (outside of a schema) and such that we use tables - seems like getting a good table in reStructuredText is just a very tricky proposition. So the table data is all still here, but the formatting is pretty crappy.

**Comment by heckj** [comment]
I also tried mixing reStructuredText format and Markdown format for rendering pages, and didn't have a tremendous amount of luck on my initial efforts. While I got sphinx to technically render it, the pages really didn't work together very well, so I suspect we'll be much better off sticking to a single markup format for this open source work (reStructuredText and the sphinx annotations), leaving markdown style documentation for light code in the individual repositories, or within wiki's assocaited with a github repository.

**Comment by heckj** [comment]
Oh - and I checked in my "source" files for any graphics. I redid some graphics from our original Theory of Operations and related documents to update names. The "*.graffle" files are the sources, created in OmniGraffle on the mac. I can convert/export to Visio if we want to head that way in the future.

**Comment by benbp** [comment]
Hahaha wow, that's too bad about the table conversion.

I'll spend some time reading through these, this is great!

**Pull request merged**
