### PR TITLE
Create a separate directory for 2.0 RackHD Users Guide

### PR DESCRIPTION
**Pull request by keedya**
- Changes to the content of this folder will be tracked in a different PR

@BillyAbildgaard @dalebremner @RackHD/corecommitters @srinia6

### CODE REVIEW

**Comment by heckj** [comment]
If you want to reference these docs from within the overall set, you'll need to update https://github.com/RackHD/docs/blob/master/docs/index.rst, and I'd recommend making updates to `docs/rackhd/index.rst` and `docs/rackhd2.0/index.rst` to make it clear that the first is the 1.1 API user's guide, and the second is the 2.0 API user's guide.

**Comment by keedya** [comment]
@heckj updated !!

**Comment by heckj** [comment]
👍

**Comment by srinia6** [comment]
+1

**Pull request merged**
