### PR TITLE
Updating QuickStart

### PR DESCRIPTION
**Pull request by bossidy**
so that it reflects the readme in the RackHD repo

### CODE REVIEW

**Comment by benbp** [comment]
Needs a rebase.

**Comment by bossidy** [comment]
I'm too git-dumb to figure out how to handle the conflicts....tried both command line and Github Desktop methods...really opaque process....

**Comment by bossidy** [comment]
Leaving soon, but will try a rebase tomorrow....

**Comment by benbp** [comment]
I started trying it out, but there was more of a change diff than I felt I could resolve accurately.

**Comment by benbp** [comment]
@bossidy a decent guide here: http://www.git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by benbp** [comment]
happy to help with any questions, hit me up on slack.

**Comment by bossidy** [comment]
Thanks for the info Ben.

**Pull request closed without merging**
