### PR TITLE
removed refs to onRack

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
@heckj @benbp 

Please do not merge yet, this is blocked.

### CODE REVIEW

**Comment by DavidjohnBlodgett** [comment]
this is blocked by https://github.com/RackHD/on-core/pull/69

**Comment by DavidjohnBlodgett** [comment]
@benbp @jlongever this is now unblocked.

**Comment by jlongever** [comment]
+1

**Comment by benbp** [comment]
:+1:

**Pull request merged**
