### PR TITLE
Adds nested navigation to the sidebar

### PR DESCRIPTION
**Pull request by rolandpoulter**
This makes the "sidenav" use a nested navigation menu see picture below.

image

### CODE REVIEW

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Comment by rolandpoulter** [comment]
@heckj @benbp

**Comment by benbp** [comment]
YES

**Comment by heckj** [comment]
retroactive +1

**Comment by christineday** [comment]
Looks great!  Thanks @rolandpoulter!!!  Do we still need the 'Docs' drop-down in the toolbar now?

**Comment by rolandpoulter** [comment]
@christineday I wanted to at least remove the dropdown in a separate PR. It is a little redundant having it now but I want to make sure it is ready to be removed.

**Pull request merged**
