### PR TITLE
video link for ReadTheDocs

### PR DESCRIPTION
**Pull request by heckj**
I tried putting in the video without removing the image, and the page looked horrifically cluttered, so took a stab with the logo in the nav bar, but removed from the main content area as it's replaced by the intro video that Kenny made for us

screen shot 2015-12-08 at 9 11 29 am

### CODE REVIEW

**Comment by heckj** [comment]
updated to just be the video link

**Comment by christineday** [comment]
looks good but in the video, do we want to use the logo with the RackHD text under it?  We created one for marketing and it's used in the youtube video's with John.  I think the toolbar logo is ok as is.

**Comment by heckj** [comment]
@christineday I switched it back to bernie's suggestion of just a video link - sec, will get you a current pic of what this PR looks like

**Comment by christineday** [comment]
works for me! thanks @heckj and @bossidy!

**Pull request merged**
