### PR TITLE
Add IPMI chassis power state alert section

### PR DESCRIPTION
**Pull request by jlongever**
@RackHD/corecommitters @zyoung51 @keedya @uppalk1 @tannoa2

### CODE REVIEW

**Comment by keedya** [comment]
:+1:

**Comment by yyscamper** [comment]
I think the doc should belong to the `Event Notification` section: http://rackhd.readthedocs.io/en/latest/rackhd2.0/notification.html

**Comment by yyscamper** [comment]
Just found we already have some history document for IPMI SEL poller, so your choice has no problem at present. Now the notification doc scattered in doc repo, we do need put them together, but not the scope of your PR.

**Comment by heckj** [comment]
👍

**Comment by anhou** [comment]
:+1:

**Pull request merged**
