### PR TITLE
testing pull request

### PR DESCRIPTION
**Pull request by christineday**

### CODE REVIEW

**Comment by benbp** [comment]
I see this is a test, but do we still want the Trademark (TM) in the official docs? It's currently not.

**Comment by heckj** [comment]
only because we haven't figured out how to make it happen properly in ReStructuredText

**Comment by benbp** [comment]
I think we can just paste in the actual unicode character ™, no?

**Comment by heckj** [comment]
resolved with https://github.com/RackHD/docs/pull/82

**Pull request closed without merging**
