### PR TITLE
Added authentication to API calls

### PR DESCRIPTION
**Pull request by dalebremner**
@RackHD/corecommitters @srinia6 @keedya @geoff-reid @BillyAbildgaard

### CODE REVIEW

**Comment by heckj** [comment]
nice @dalebremner, thank you!

👍

**Comment by brianparry** [comment]
:+1:

**Comment by keedya** [comment]
:+1:

**Comment by zyoung51** [comment]
Is it worth mentioning the ?auth_token query string support in addition to the header option?

**Pull request merged**
