### PR TITLE
fix docs for logColorEnable/httpProxies, and fix some style error

### PR DESCRIPTION
**Pull request by yyscamper**
1. Add docs for configuration `logColorEnable`
2. Fix some docs for 'httpProxies`
3. Fix some style errors

### CODE REVIEW

**Comment by yyscamper** [comment]
@heckj @RackHD/corecommitters @pengz1 @WangWinson @cgx027 @iceiilin

**Comment by cgx027** [comment]
:+1: Looks good to me.

**Comment by pengz1** [comment]
+1

**Comment by WangWinson** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Pull request merged**
