### PR TITLE
adding mention of community mailing lists and chat

### PR DESCRIPTION
**Pull request by heckj**

### CODE REVIEW

**Comment by heckj** [comment]
@bossidy @christineday

**Comment by bossidy** [comment]
We already have that info in near the bottom of the same page...

**Comment by heckj** [comment]
sorry, you're right - totally didn't see it. Closing.

**Comment by bossidy** [comment]
BTW, on another subject, you are planning on making substantial additions/changes to getting_started.rst. Correct?

Just verifying so I will stay away from that file for the time being...

**Comment by heckj** [comment]
I was going to focus on the quick start pieces - I've got https://github.com/RackHD/RackHD/pull/14/files up right now that makes the system functional and nails down a README that I was going to port into these docs once it's merged

**Comment by bossidy** [comment]
Thanks. You're a pretty busy guy.....

**Pull request closed without merging**
