### PR TITLE
Updating the obmsettings ipmi-obm-service

### PR DESCRIPTION
**Pull request by tldavies**
The ObmSettings service format was update and some documentation was missed. Updating old documentation.

### CODE REVIEW

**Comment by tldavies** [comment]
@gpaulos @brianparry 

@RackHD/corecommitters

**Comment by brianparry** [comment]
:+1: Thanks @tldavies!

**Comment by DavidjohnBlodgett** [comment]
👍

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
